"""""""""""""""""""""""pathogen"""""""""""""""""""""""""""
call pathogen#infect()




"""""""""""""""""""""""Normal"""""""""""""""""""""""""""
"显示当前模式
set showmode

"显示行号
set number

"显示当前光标
set cursorline                                                                                                      

"取消折行
set nowrap     

"设置制表符显示格式
"set list
set listchars=tab:>-,trail:-

"搜索时忽略大小写
set ignorecase

"搜索高亮显示
set hlsearch

"搜索在键入目标字符串时就开始
set incsearch

"搜索到达文件开头或末尾自动循环
set wrapscan

"显示光标位置
set ruler

"显示当前命令
set laststatus=2

"语法高亮
syntax on/enable

"设置缩进
set autoindent
set softtabstop=4
set shiftwidth=4
set et
set smarttab

"装入对应文件的类型的设置
filetype plugin on
filetype indent on

"其它设置
set noerrorbells
set nobackup
setlocal noswapfile
set viminfo+=!




"""""""""""""""""""""""map"""""""""""""""""""""""""""
"map <C-l> :tabn<CR> 
"map <C-h> :tabp<CR>




"""""""""""""""""""""""plugin"""""""""""""""""""""""""""
"tagbar
"autocmd BufRead * Tagbar
nmap <F9> :TagbarToggle<CR>

"NERDTree
map <F3> :NERDTreeToggle<CR>
let NERDTreeWinPos="left"
let NERDTreeShowBookmarks=1

"unite
"let g:unite_force_overwrite_statusline = 0
call unite#custom#profile('default', 'context', {
\   'start_insert': 0,
\   'winheight': 10,
\   'direction': 'botright',
\ })


"ctrlp
"let g:ctrlp_cache_dir = $HOME.'/.cache/ctrlp'
let g:ctrlp_use_caching = 1
let g:ctrlp_clear_cache_on_exit = 0
let g:ctrlp_max_files = 0
let g:ctrlp_working_path_mode = 'w'
let g:ctrlp_match_window = 'bottom,order:ttb,min:1,max:10,results:10'
let g:ctrlp_switch_buffer = 'Et'
let g:ctrlp_open_new_file = 't'
let g:ctrlp_tabpage_position = 'ac'
let g:ctrlp_open_multiple_files = 't'
let g:ctrlp_lazy_update = 0
let g:ctrlp_regexp = 0
let g:ctrlp_show_hidden = 0
let g:ctrlp_by_filename = 1
let g:ctrlp_custom_ignore = {
    \ 'dir':  '\v[\/]\.(git|hg|svn)$',
    \ 'file': '\v\.(exe|so|dll|a|jpg|png)$',
    \ 'link': 'SOME_BAD_SYMBOLIC_LINKS',
    \ }
"let g:ctrlp_user_command = 'find %s -type f'

"flake8
"autocmd BufWritePost *.py call Flake8()
"map <F5> :call Flake8()
let g:flake8_ignore="E501"

"markdown
let g:vim_markdown_folding_disabled=1
let g:vim_markdown_initial_foldlevel=1

"molokai
let g:molokai_original = 1
let g:rehash256 = 1

"""""""""""""""""""""""Vim color file"""""""""""""""""""""""""""
"http://vimcolorschemetest.googlecode.com/svn/html/index-html.html
